BEGIN TRANSACTION;
CREATE TABLE Charakter (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE Notiz (id INTEGER PRIMARY KEY, charakter_id NUMERIC, geschichte NUMERIC, inhalt TEXT);
CREATE TABLE Tag (tag TEXT, notiz_id NUMERIC);
COMMIT;
